/**
 * ReactNativeRunner — VitestRunner implementation for Hermes/RN.
 */

import type { VitestRunner, VitestRunnerConfig, File, Test } from '@vitest/runner';
import { cleanup } from './render';
import { waitForContainerReady } from './context';
import { setupExpect } from './expect-setup';
import { symbolicateErrors } from './symbolicate';

interface RuntimeRpcBridge {
  onCollected(files: File[]): void;
  onTaskUpdate(packs: any[], events?: any[]): void;
  onUnhandledError(err: unknown, type: string): void;
}

type TestCallback = (test: Test) => void;

export class ReactNativeRunner implements VitestRunner {
  config: VitestRunnerConfig;
  private rpc: RuntimeRpcBridge;
  private onTestDone?: TestCallback;

  constructor(config: VitestRunnerConfig, rpc: RuntimeRpcBridge, onTestDone?: TestCallback) {
    this.config = config;
    this.rpc = rpc;
    this.onTestDone = onTestDone;
  }

  async onBeforeRunFiles(_files: File[]): Promise<void> {
    await waitForContainerReady();
    setupExpect();
  }

  importFile(filepath: string, source: 'collect' | 'setup'): unknown {
    // Load the virtual test registry generated by the pool
    let registry: { testFiles: Record<string, () => void> };
    try {
      registry = require('vitest-react-native-runtime/test-registry');
    } catch {
      console.error('[runner] Could not load test registry');
      return undefined;
    }

    // Try exact match first, then suffix match
    const loader =
      registry.testFiles[filepath] ||
      registry.testFiles['./' + filepath] ||
      (Object.values(
        Object.entries(registry.testFiles).find(([key]) => filepath.endsWith(key.replace('./', ''))) || {},
      )[1] as (() => void) | undefined);

    if (loader) {
      loader();
    } else {
      console.warn(`[runner] File not found in registry: ${filepath}`);
      console.warn(`[runner] Available:`, Object.keys(registry.testFiles));
    }

    return undefined;
  }

  onCollected(files: File[]): void {
    this.rpc.onCollected(files);
  }

  async onAfterRunTask(test: Test): Promise<void> {
    if (test.result?.state === 'fail') {
      await symbolicateErrors(test.result);
    }
    this.rpc.onTaskUpdate([[test.id, test.result, test.meta]], []);
    this.onTestDone?.(test);
    await cleanup();
  }
}
