import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      'node/index': 'src/node/index.ts',
      'node/pool': 'src/node/pool.ts',

      'node/environment': 'src/node/environment.ts',
      'node/device': 'src/node/device/index.ts',
    },
    format: ['esm', 'cjs'],
    dts: false,
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: true,
    shims: true,
    external: ['metro', 'metro-config'],
  },
  {
    entry: {
      'runtime/index': 'src/runtime/index.ts',
      'runtime/vitest-shim': 'src/runtime/vitest-shim.ts',
      'runtime/test-context': 'src/runtime/test-context.ts',
    },
    format: ['cjs'],
    outDir: 'dist',
    target: 'es2022',
    platform: 'neutral',
    splitting: false,
    sourcemap: true,
    clean: false,
    external: [
      'react',
      'react-native',
      '@vitest/runner',
      '@vitest/expect',
      '@vitest/utils',
      'birpc',
      'flatted',
      'chai',
      'vitest-mobile/test-context',
      '@shopify/restyle',
      'signalium',
      'signalium/react',
    ],
  },
  {
    entry: {
      'babel/test-wrapper-plugin': 'src/babel/test-wrapper-plugin.ts',
      'babel/vitest-compat-plugin': 'src/babel/vitest-compat-plugin.ts',
      'babel/inline-app-root-plugin': 'src/babel/inline-app-root-plugin.ts',
    },
    format: ['cjs'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
  },
  {
    entry: { 'cli/index': 'src/cli/index.ts' },
    format: ['esm'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
    external: ['vite'],
  },
]);
